// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBpFGhvUZURRuyBf7Nc42QGt29alznIcw',
    appId: '1:799945204583:web:a1d926a42108224be445c2',
    messagingSenderId: '799945204583',
    projectId: 'lonchiinggd',
    authDomain: 'lonchiinggd.firebaseapp.com',
    storageBucket: 'lonchiinggd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBla2OQdoqQFenPYqeRL0ZAb54Su_9GxF4',
    appId: '1:799945204583:android:5bd80268db25d8ede445c2',
    messagingSenderId: '799945204583',
    projectId: 'lonchiinggd',
    storageBucket: 'lonchiinggd.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBpFGhvUZURRuyBf7Nc42QGt29alznIcw',
    appId: '1:799945204583:web:a1d926a42108224be445c2',
    messagingSenderId: '799945204583',
    projectId: 'lonchiinggd',
    authDomain: 'lonchiinggd.firebaseapp.com',
    storageBucket: 'lonchiinggd.appspot.com',
  );

}