name: Build iOS IPA (unsigned)

# Trigger manually or on push to main branch
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest
#    env:
#      SWIFT_VERSION: "5.9"
#      DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer

    steps:
      #1. Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v4

      #2. Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.35.6
          architecture: x64

      #3. Precache ios artifacts
      - name: Precache Flutter iOS artifacts
        run: |
          flutter precache --ios

      #4. Simplified cleanup
      - name: Clean Flutter project
        run: |
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock pubspec.lock
          flutter pub cache repair

      #5. Get Flutter dependencies
      - name: Get Flutter dependencies
        run: |
          flutter pub get

      #6. Create Podfile if missing
      - name: Create Podfile for CI
        run: |
          mkdir -p ios
          cat <<'EOF' > ios/Podfile
          platform :ios, '15.0'
          
          use_frameworks!
          use_modular_headers!
      
          ENV['COCOAPODS_DISABLE_STATS'] = 'true'

          flutter_root = ENV['FLUTTER_ROOT']
          require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)
          flutter_ios_podfile_setup

          target 'Runner' do
            flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
          end
      
          post_install do |installer|
            installer.pods_project.targets.each do |target|
            puts "Configuring pod target: #{target.name}"
              target.build_configurations.each do |config|
                config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
                config.build_settings['SWIFT_VERSION'] = '5.0'
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
                config.build_settings['HEADER_SEARCH_PATHS'] ||= '$(inherited)'
                config.build_settings['HEADER_SEARCH_PATHS'] << ' $(PROJECT_DIR)/Flutter'
                config.build_settings['HEADER_SEARCH_PATHS'] << ' $(PROJECT_DIR)/Flutter/Flutter.framework/Headers'
                config.build_settings['HEADER_SEARCH_PATHS'] << ' $(PROJECT_DIR)/Flutter/Flutter.xcframework/ios-arm64/Flutter.framework/Headers'
                config.build_settings['HEADER_SEARCH_PATHS'] << ' $(PROJECT_DIR)/Flutter/Flutter.xcframework/ios-arm64_x86_64-simulator/Flutter.framework/Headers'
                config.build_settings['HEADER_SEARCH_PATHS'] << '$(PROJECT_DIR)/Flutter/Flutter.xcframework/ios-arm64/Flutter.framework/Modules'
                config.build_settings['HEADER_SEARCH_PATHS'] << '$(PROJECT_DIR)/Flutter/Flutter.xcframework/ios-arm64_x86_64-simulator/Flutter.framework/Modules'
                config.build_settings['HEADER_SEARCH_PATHS'] << ' $(FLUTTER_ROOT)/bin/cache/artifacts/engine/ios-release/Flutter.xcframework/ios-arm64/Flutter.framework/Headers'
                config.build_settings['FRAMEWORK_SEARCH_PATHS'] ||= '$(inherited)'
                config.build_settings['FRAMEWORK_SEARCH_PATHS'] << ' $(PROJECT_DIR)/Flutter'
              end
            end
            flutter_post_install(installer) if defined?(flutter_post_install)
          end
          EOF
          echo "Podfile written to ios/Podfile"

      #7. Install CocoaPods
      - name: Install CocoaPods
        working-directory: ios
        run: |
          rm -rf Pods Podfile.lock
          pod repo update
          pod install --repo-update
        env:
          COCOAPODS_DISABLE_STATS: 'true'

      #8. Check Wakelock headers include path
      - name: Check Wakelock headers include path
        run: |
          grep -R "HEADER_SEARCH_PATHS" ios/Pods/Pods.xcodeproj/project.pbxproj | head -n 30

      #9. Show pod & engine artifacts state (debug)
      - name: Show pod & engine artifacts state (debug)
        run: |
          echo "Podfile:"
          sed -n '1,200p' ios/Podfile || true
          echo "---- Podfile.lock head ----"
          head -n 60 ios/Podfile.lock || true
          echo "---- Flutter engine folder ----"
          ls -al $FLUTTER_ROOT/bin/cache/artifacts/engine/ios || true
          echo "---- Pods installed ----"
          ls -al ios/Pods || true

      #10. Build unsigned iOS IPA
      - name: Build unsigned iOS IPA
        run: flutter build ipa --no-codesign --verbose

      #11. Upload IPA as artifact
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-ipa
          path: build/ios/ipa/*.ipa
