name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios-ipa:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - run: flutter pub get


      - name: Ensure Podfile sets iOS 15.0
        run: |
          mkdir -p ios
          cat <<'EOF' > ios/Podfile
          platform :ios, '15.0'
          
          use_frameworks!
          use_modular_headers!
          
          ENV['COCOAPODS_DISABLE_STATS'] = 'true'
          
          flutter_root = ENV['FLUTTER_ROOT']
          require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)
          flutter_ios_podfile_setup
          
          target 'Runner' do
            flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
          end
          
          post_install do |installer|
            installer.pods_project.targets.each do |target|
              target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
              end
            end
            flutter_post_install(installer) if defined?(flutter_post_install)
          end
          EOF
          echo "✅ Podfile created for iOS 15.0"

      - run: pod repo update
        working-directory: ios

      - run: flutter build ios --release --no-codesign

      - run: mkdir Payload
        working-directory: build/ios/iphoneos

      - run: mv Runner.app/ Payload
        working-directory: build/ios/iphoneos

      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is first release"