name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios-ipa:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Setup Bundler and CocoaPods 1.16.2
        run: |
          sudo gem install bundler
          echo "source 'https://rubygems.org'" > Gemfile
          echo "gem 'cocoapods', '1.16.2'" >> Gemfile
          bundle install
          bundle exec pod --version

      - name: Ensure Podfile sets iOS 15.0
        run: |
          mkdir -p ios
          cat <<'EOF' > ios/Podfile
          platform :ios, '15.0'
          
          use_frameworks!
          use_modular_headers!
          
          ENV['COCOAPODS_DISABLE_STATS'] = 'true'
          
          flutter_root = ENV['FLUTTER_ROOT']
          require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)
          flutter_ios_podfile_setup
          
          target 'Runner' do
            flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
          end
          
          post_install do |installer|
            installer.pods_project.targets.each do |target|
              target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
              end
            end
            flutter_post_install(installer) if defined?(flutter_post_install)
          end
          EOF
          echo "✅ Podfile created for iOS 15.0"

      - name: Clean iOS Pods
        run: |
          rm -rf ios/Pods ios/Podfile.lock ios/Flutter/Flutter.framework ios/Flutter/Flutter.xcframework

      - name: Install CocoaPods dependencies
        working-directory: ios
        run: bundle exec pod install

      - name: Build iOS IPA (no code sign)
        run: |
          flutter clean
          flutter pub get
          flutter build ipa --no-codesign --verbose

      - name: Prepare IPA
        run: |
          mkdir -p build/ios/iphoneos/Payload
          mv build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload/
          cd build/ios/iphoneos
          zip -qq -r -9 FlutterIpaExport.ipa Payload

      - name: Upload IPA to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is first release"
